# Generated by Django 5.1.2 on 2025-03-31 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=100)),
                ('prixTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sortie',
                'verbose_name_plural': 'Sorties',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('Administrateur', 'Administrateur'), ('Gestionnaire de stock', 'Gestionnaire de stock'), ('Consultant', 'Consultant')], max_length=50)),
                ('valide', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='static/users/photodeprofil/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='stocks.fournisseur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='stocks.user')),
            ],
            options={
                'verbose_name': 'Entrée',
                'verbose_name_plural': 'Entrées',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('categorie', models.CharField(max_length=255)),
                ('quantite_fournie', models.PositiveIntegerField()),
                ('quantite_disponible', models.PositiveIntegerField()),
                ('unite_mesure', models.CharField(choices=[('kg', 'Kilogramme'), ('litre', 'Litre'), ('unité', 'Unité')], max_length=10)),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_peremption', models.DateField()),
                ('entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees', to='stocks.entree')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='ProduitSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_sortie', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_sortie', to='stocks.produit')),
                ('sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortiesId', to='stocks.sortie')),
            ],
            options={
                'verbose_name': 'Produit sortie',
                'verbose_name_plural': 'Produits sorties',
            },
        ),
        migrations.AddField(
            model_name='sortie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs_sortie', to='stocks.user'),
        ),
    ]
