# Generated by Django 5.1.2 on 2025-04-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitsortie',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='motif',
            field=models.CharField(choices=[('Vente', 'Vente'), ('Utilisations internes', 'Utilisations internes'), ('Destructions(Produits périmés)', 'Destructions(Produits périmés)'), ('Transferts entre entrepôts', 'Transferts entre entrepôts')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('', '---- Sélectionnez un rôle ----'), ('Administrateur', 'Administrateur'), ('Gestionnaire de stock', 'Gestionnaire de stock'), ('Consultant', 'Consultant')], max_length=50),
        ),
    ]
