# Generated by Django 5.1.2 on 2025-04-07 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_produitsortie_nom_alter_sortie_motif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitsortie',
            name='nom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='produits_sortie', to='stocks.produit'),
        ),
    ]
