# Generated by Django 5.1.2 on 2025-04-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_produitsortie_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitsortie',
            old_name='prix',
            new_name='prixTotal',
        ),
        migrations.AddField(
            model_name='produitsortie',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
