# Generated by Django 5.1.2 on 2025-04-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_rename_prix_produitsortie_prixtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsortie',
            name='reference',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produitsortie',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
